@ChatbotApi_HostAddress = http://localhost:5220

POST {{ChatbotApi_HostAddress}}/api/Chat/company
Accept: application/json
Content-Type: application/json
{
  "question": "Tell me a joke about a cat"
}

###